name: sbom creation

on:
  release:
    types: [published]
  # push:
    # branches:
      # - main
  # pull_request:

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: |
          syft dir:. -o cyclonedx-json > sbom.json

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan for Vulnerabilities and Save to File
        run: |
          grype sbom:sbom.json -o table > vulnerabilities.txt || true

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Upload SBOM to Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: sbom.json

      - name: Upload Vulnerabilities Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulnerabilities
          path: vulnerabilities.txt

      - name: Upload Vulnerabilities to Release
        uses: softprops/action-gh-release@v2
        with:
          files: vulnerabilities.txt
